app/routes/query/__init__.py
from flask import Blueprint, g

bp = Blueprint('query', __name__)

@bp.url_defaults
def add_language_code(endpoint, values):
    if 'lang_code' not in g:
        g.lang_code = 'de'  # or your default language
    values.setdefault('lang_code', g.lang_code)


@bp.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')

from app.routes.query import routes

app/routes/query/routes.py
from flask import render_template, request, url_for, flash, redirect
from flask_login import login_required
from flask_babel import _

from app.forms.forms import QueryForm
from app.models.model import Peak, Spectrum, Compound, Intensity
from app.routes.query import bp
from app.extensions import db


@bp.route('/query', methods=['GET'])
@login_required
def query():
    """
        Query page for finding spectra based on given wavenumbers, only accessible for logged in users

    Returns:
        rendered template of the query page, with the form for creating a new query
    """
    form = QueryForm()
    return render_template('resources/query/index.html', form=form)


def get_form_data(form):
    """
        Get the data from the form and return it as a dictionary

    Args:
        form (request.form): a dictionary-like object containing the data from the form

    Returns:
        data (dict): a dictionary containing the wavenumbers and intensities from the form
    """
    # get evey key-value pair from the form where the key contains '_intensity'
    data = {float(k.lstrip("wn-")): float(v) for k, v in form.items() if 'wn-' in k and v != ''}
    return data, float(form['tolerance'])


@bp.route('/query', methods=['POST'])
@login_required
def query_post():
    """
        executes the query with the specified parameters and returns the result, only accessible for logged in users

    Returns:
        based on the validation of the form, either renders the result page or
        renders the query page again with validation errors
    """

    # extract data from request.form
    data, tolerance = get_form_data(request.form)

    # check if at least one wavenumber was given
    # if one wavenumber was given, and the rest of the form is empty, the form is valid
    if  len(data) == 0:
        flash(_('Bitte geben Sie mindestens eine Wellenzahl an.'), 'danger')
        return redirect(url_for('query.query'))

    # query peaks table for peaks within the range wavenumber-tolerance and wavenumber+tolerance
    wavenumbers = {}
    cnt = 0
    for wavenumber in data.values():
        # get all matching peaks
        peaks = db.session.query(Peak).filter(
            Peak.wavenumber.between(wavenumber - tolerance, wavenumber + tolerance)).all()
        if len(peaks) == 0:
            continue
        result = []
        # transform the peaks into a dictionary for easier access in the template
        for peak in peaks:
            result_element = {}
            spectrum = db.session.query(Spectrum).filter(Spectrum.id == peak.spectrum_id).first()
            compound = db.session.query(Compound).filter(Compound.id == spectrum.compound_id).first()
            result_element['compound'] = compound.name
            result_element['compound_id'] = compound.id
            result_element['exact_wavenumber'] = peak.wavenumber
            result_element['intensity'] = db.session.query(Intensity).filter(
                Intensity.id == peak.intensity_id).first().shorthand
            result.append(result_element)
            cnt += 1
        wavenumbers[wavenumber] = result
    return render_template('resources/query/result.html', result=dict(sorted(wavenumbers.items())), tolerance=tolerance, cnt=cnt)

app/routes/ramanbands/__init__.py
from flask import Blueprint, g

bp = Blueprint('ramanband', __name__)

@bp.url_defaults
def add_language_code(endpoint, values):
    if 'lang_code' not in g:
        g.lang_code = 'de'  # or your default language
    values.setdefault('lang_code', g.lang_code)


@bp.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')

from app.routes.ramanbands import routes

app/routes/ramanbands/routes.py
import sqlalchemy.exc
from flask import render_template, request, url_for, flash, redirect
from flask_login import login_required, current_user
from flask_babel import _
from sqlalchemy import desc

from app.forms.forms import RamanBandForm, RamanBandQueryForm
from app.routes.ramanbands import bp
from app.models.model import RamanBands, RamanBandAssignment, RamanBandCategory, Intensity
from app.extensions import db


@bp.route('/')
@login_required
def index():
    bands = db.session.query(RamanBands).order_by(RamanBands.wavenumber).all()

    return render_template('resources/ramanbands/index.html', bands=bands)


def build_ramanband_form():
    categories = db.session.query(RamanBandCategory).all()
    intensities = db.session.query(Intensity).all()
    form = RamanBandForm()
    form.bandCategory.choices = [(c.id, c.name) for c in categories]
    form.bandAmplitude.choices = [(i.id, str(i.shorthand) + " (" + str(i.description) + ")") for i in intensities]
    return form


@bp.route('/new', methods=['GET'])
@login_required
def new():
    """
        Create page for raman bands, only accessible for logged in users

    Returns:
        rendered template of the new page, with the form for creating a new raman band
    """
    form = build_ramanband_form()
    return render_template('resources/ramanbands/new.html', form=form)


@bp.route('/new', methods=['POST'])
@login_required
def new_post():
    """
        Creates a new laser, only accessible for logged in users

    Returns:
        based on the validation of the form, either redirects to this resources index page or
        renders the Create page again with validation errors (WTForms) or integrity errors (SQL constraints)
    """
    # convert request.form to form object
    form = RamanBandForm(request.form)
    categories = db.session.query(RamanBandCategory).all()
    intensities = db.session.query(Intensity).all()
    form.bandCategory.choices = [(c.id, c.name) for c in categories]
    form.bandAmplitude.choices = [(i.id, str(i.shorthand) + " (" + str(i.description) + ")") for i in intensities]

    # if the form is not valid, redirect to the new page and pass the values from the form
    if not form.validate():
        return render_template('resources/ramanbands/new.html', form=form)
    # if the form is valid, create a new lens and redirect to the index page
    else:
        # if unique constraint is violated, inform the user
        try:
            wavenumber = form.wavenumber.data
            bandType = form.bandType.data
            bandCategory = form.bandCategory.data
            bandAmplitude = form.bandAmplitude.data
            author = form.author.data
            doi = form.doiLink.data

            bandAssignment = RamanBandAssignment(bandType=bandType, bandCategoryId=bandCategory,
                                                 bandAmplitudeId=bandAmplitude, author=author, doiLink=doi)

            db.session.add(bandAssignment)
            db.session.commit()

            band = RamanBands(wavenumber=wavenumber, bandAssignmentId=bandAssignment.id)
            db.session.add(band)
            db.session.commit()

            return redirect(url_for('ramanband.index'))
        except sqlalchemy.exc.IntegrityError:
            flash(_('Diese Kategorie existiert bereits'), 'danger')
            return render_template('resources/ramanbands/new.html', form=form)


@bp.route('/<band_id>/edit', methods=['GET'])
@login_required
def edit(band_id):
    """
        Edit page for raman band, only accessible for logged in users

    Args:
        band_id (int): id of the band to be edited

    Returns:
        rendered template of the edit page, with the form for editing a band
    """
    band = db.session.query(RamanBands).filter(RamanBands.id == band_id).first()
    form = build_ramanband_form()
    form.doiLink.data = band.bandAssignment.doiLink
    form.author.data = band.bandAssignment.author
    form.bandAmplitude.data = str(band.bandAssignment.bandAmplitudeId)
    form.bandCategory.data = str(band.bandAssignment.bandCategoryId)
    form.bandType.data = band.bandAssignment.bandType
    form.wavenumber.data = band.wavenumber
    return render_template('resources/ramanbands/edit.html', form=form)


@bp.route('/<band_id>/edit', methods=['POST'])
@login_required
def edit_post(band_id):
    """
        Edits the raman band, only accessible for logged in users

    Args:
        band_id (int): id of the raman band to be edited

    Returns:
        based on the validation of the form, either redirects to this resources index page or
        renders the Edit page again with validation errors (WTForms) or integrity errors (SQL constraints)
    """
    # convert request.form to form object
    form = RamanBandForm(request.form)
    categories = db.session.query(RamanBandCategory).all()
    intensities = db.session.query(Intensity).all()
    form.bandCategory.choices = [(c.id, c.name) for c in categories]
    form.bandAmplitude.choices = [(i.id, str(i.shorthand) + " (" + str(i.description) + ")") for i in intensities]

    # if the form is not valid, redirect to the new page and pass the values from the form
    if not form.validate():
        print(form.wavenumber.data)
        return render_template('resources/ramanbands/edit.html', form=form)
        # if the form is valid, create a new lens and redirect to the index page
    else:
        # if unique constraint is violated, inform the user
        try:
            ramanband = db.session.query(RamanBands).filter(RamanBands.id == band_id).first()
            bandAssignment = ramanband.bandAssignment

            ramanband.wavenumber = form.wavenumber.data

            bandAssignment.bandType = form.bandType.data
            bandAssignment.bandCategoryId = form.bandCategory.data
            bandAssignment.bandAmplitudeId = form.bandAmplitude.data
            bandAssignment.author = form.author.data
            bandAssignment.doiLink = form.doiLink.data

            db.session.commit()
            return redirect(url_for('ramanband.index'))
        except sqlalchemy.exc.IntegrityError:
            flash(_('Dieses Raman-Band existiert bereits'), 'danger')
            return render_template('resources/ramanbands/edit.html', form=form)


@bp.route('/<band_id>/delete')
@login_required
def delete(band_id):
    """
        Deletes the band  if not used in a compound, only accessible for logged in users

    Args:
        band_id (int): id of the band to be deleted

    Returns:
        redirects to the index page, with a flash message based on the success of the deletion
    """
    try:
        category = db.session.query(RamanBands).filter(RamanBands.id == band_id).first()
        db.session.delete(category)
        db.session.commit()
        flash(_("Raman-Band wurde gelöscht"), 'success')
        return redirect(url_for('ramanband.index'))
    except sqlalchemy.exc.IntegrityError:
        flash(_('Dieses Raman-Band wird noch verwendet und kann daher nicht gelöscht werden.'), 'danger')
        return redirect(url_for('ramanband.index'))
    except:
        flash(_('Raman-Band konnte nicht gelöscht werden. Probieren Sie es später erneut.'), 'danger')
        return redirect(url_for('ramanband.index'))


def build_ramanbandquery_form():
    categories = db.session.query(RamanBandCategory).all()
    intensities = db.session.query(Intensity).all()
    form = RamanBandQueryForm()
    categories = [(c.id, c.name) for c in categories]
    categories.insert(0, (0, 'Alle'))
    form.bandCategory.choices = categories
    return form


@bp.route('/query', methods=['GET'])
@login_required
def query():
    """
            Query page for raman bands, only accessible for logged in users

        Returns:
            rendered template of the query page, with the form for querying a raman band
        """
    form = build_ramanbandquery_form()

    return render_template('resources/ramanbands/query.html', form=form, initial=True)


@bp.route('/query', methods=['POST'])
@login_required
def query_post():
    """
    Queries the database for raman bands that match the filters, only accessible for logged in users

    Returns:
        a rendered template of the query page, with the form for querying a raman band and the results of the query
        """
    # convert request.form to form object
    form = RamanBandQueryForm(request.form)
    categories = db.session.query(RamanBandCategory).all()

    categories = [(c.id, c.name) for c in categories]
    categories.insert(0, (0, 'Alle'))
    form.bandCategory.choices = categories


    # if the form is not valid, redirect to the new page and pass the values from the form
    if not form.validate():
        return render_template('resources/ramanbands/query.html', form=form, initial=True)
        # if the form is valid, create a new lens and redirect to the index page
    else:
        # query the database using the provided filter values
        wavenumber = form.wavenumber.data
        bandCategory = form.bandCategory.data
        bandType = form.bandType.data

        queryfilter = db.session.query(RamanBands).join(RamanBandAssignment)

        if wavenumber:
            queryfilter = queryfilter.filter(RamanBands.wavenumber == wavenumber)

        if bandType:
            queryfilter = queryfilter.filter(RamanBandAssignment.bandType.contains(bandType))

        if bandCategory != '0':  # 0 is the value for "all"
            queryfilter = queryfilter.filter(RamanBandAssignment.bandCategoryId == bandCategory)

        bands = queryfilter.order_by(RamanBands.wavenumber).all()

        return render_template('resources/ramanbands/query.html', form=form, bands=bands, initial=False)

app/templates/resources/ramanbands/edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3 content">

        <a class="icon-link icon-link-hover mb-2"
           style="--bs-icon-link-transform: translate3d(-.125rem, 0, 0); --bs-link-color-rgb: 97,100,102;"
           href="{{ url_for('ramanband.index') }}">
            <i class="bi bi-arrow-left mb-auto"></i>
            {{ _('Zurück')}}
        </a>
        <h1>{{ _('Bearbeiten') }} <b><em>{{ _('Raman-Bande') }}</em></b></h1>
        {% include 'includes/errors.html' %}
        <form method="POST" novalidate>
            {{ form.csrf_token }}
            <div class="row">
                <div class="col-12 col-md-6 mb-3">
                    {{ form.wavenumber.label(class="form-label") }}
                    {{ form.wavenumber(class="form-control", placeholder="1260") }}
                    {% if form.wavenumber.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.wavenumber.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="col-12 col-md-6 mb-3">
                    {{ form.bandType.label(class="form-label") }}
                    {{ form.bandType(class="form-control", placeholder=_("CH2 Schwingung")) }}
                    {% if form.bandType.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.bandType.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-6 mb-3">
                    {{ form.bandCategory.label(class="form-label") }}
                    {{ form.bandCategory(class="form-control", placeholder="1260") }}
                    {% if form.bandCategory.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.bandCategory.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="col-12 col-md-6 mb-3">
                    {{ form.bandAmplitude.label(class="form-label") }}
                    {{ form.bandAmplitude(class="form-control", placeholder=_("CH2 Schwingung")) }}
                    {% if form.bandAmplitude.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.bandAmplitude.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-6 mb-3">
                    {{ form.author.label(class="form-label") }}
                    {{ form.author(class="form-control", placeholder=_("Max Mustermann")) }}
                    {% if form.author.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.author.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="col-12 col-md-6 mb-3">
                    {{ form.doiLink.label(class="form-label") }}
                    {{ form.doiLink(class="form-control", placeholder=" https://doi.org/10.1080/14729679.2018.1507831") }}
                    {% if form.doiLink.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.doiLink.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">{{ _('Speichern') }}</button>
        </form>
    </div>
{% endblock %}

app/templates/resources/ramanbands/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3 content">

        {% include 'includes/backToStart.html' %}
        {% include 'includes/errors.html' %}
        <div class="row">
            <div class="col-12 col-md-6 d-flex align-items-center justify-content-start">
                <h1>{{_('Übersicht')}} <b><em>{{ _('Raman Banden')}}</em></b></h1>
            </div>
            <div class="col-12 col-md-6 d-flex align-items-center justify-content-start justify-content-md-end">
                <a type="button" class="btn btn-outline-success btn-sm" href="{{ url_for('ramanband.new') }}"><i
                        class="bi bi-plus-lg"></i>
                    {{ _('Neue Bande erstellen')}}
                </a>
            </div>
        </div>
        {% if bands|length<=0 %}
            <h4>{{ _('Es sind noch keine Banden hinterlegt')}}</h4>
        {% else %}
            <table class="table table-fixed">
                <thead>
                <tr>
                    <th scope="col">{{ _('Wellenzahl [cm<sup>-1</sup>]')}}</th>
                    <th>{{ _('Schwingungsart') }}</th>
                    <th>{{ _('Kategorie') }}</th>
                    <th>{{ _('Intensität')}}</th>
                    <th>{{ _('DOI') }}</th>
                    <th>{{ _('Aktionen') }}</th>
                </tr>
                </thead>
                <tbody>
                {% for band in bands %}

                    <tr>
                        <td>{{ band.wavenumber }}</td>
                        <td>{{ band.bandAssignment.bandType }}</td>
                        <td>{{ band.bandAssignment.bandCategory.name }}</td>
                        <td>{{ band.bandAssignment.bandAmplitude.description }}</td>
                        <td><a href="{{ band.bandAssignment.doiLink }}" target="_blank">{{_('Öffnen')}}</a></td>
                        <td>
                            <a type="button" class="btn btn-outline-primary btn-sm my-1"
                               href="{{ url_for('ramanband.edit', band_id=band.id) }}"><i class="bi bi-pencil-fill"></i>
                                {{ _('Bearbeiten') }}</a>
                            <a type="button" class="btn btn-outline-danger btn-sm my-1"
                               href="{{ url_for('ramanband.delete', band_id=band.id) }}"><i
                                    class="bi bi-trash-fill"></i>
                                {{ _('Löschen')}}</a>
                        </td>
                    </tr>

                {% endfor %}
            </table>
        {% endif %}
    </div>
{% endblock %}

app/templates/resources/ramanbands/new.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3 content">

        <a class="icon-link icon-link-hover mb-2"
           style="--bs-icon-link-transform: translate3d(-.125rem, 0, 0); --bs-link-color-rgb: 97,100,102;"
           href="{{ url_for('ramanband.index') }}">
            <i class="bi bi-arrow-left mb-auto"></i>
            {{ _('Zurück')}}
        </a>
        <h1>{{ _('Erstellen') }} <b><em>{{ _('Raman-Bande') }}</em></b></h1>
        {% include 'includes/errors.html' %}
        <form method="POST" novalidate>
            {{ form.csrf_token }}
            <div class="row">
                <div class="col-12 col-md-6 mb-3">
                    {{ form.wavenumber.label(class="form-label") }}
                    {{ form.wavenumber(class="form-control", placeholder="1260") }}
                    {% if form.wavenumber.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.wavenumber.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="col-12 col-md-6 mb-3">
                    {{ form.bandType.label(class="form-label") }}
                    {{ form.bandType(class="form-control", placeholder=_("CH2 Schwingung")) }}
                    {% if form.bandType.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.bandType.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-6 mb-3">
                    {{ form.bandCategory.label(class="form-label") }}
                    {{ form.bandCategory(class="form-control", placeholder="1260") }}
                    {% if form.bandCategory.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.bandCategory.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="col-12 col-md-6 mb-3">
                    {{ form.bandAmplitude.label(class="form-label") }}
                    {{ form.bandAmplitude(class="form-control", placeholder=_("CH2 Schwingung")) }}
                    {% if form.bandAmplitude.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.bandAmplitude.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-6 mb-3">
                    {{ form.author.label(class="form-label") }}
                    {{ form.author(class="form-control", placeholder=_("Max Mustermann")) }}
                    {% if form.author.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.author.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="col-12 col-md-6 mb-3">
                    {{ form.doiLink.label(class="form-label") }}
                    {{ form.doiLink(class="form-control", placeholder=" https://doi.org/10.1080/14729679.2018.1507831   ") }}
                    {% if form.doiLink.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.doiLink.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
                    <button type="submit" class="btn btn-primary">{{ _('Erstellen') }}</button>


        </form>
    </div>
{% endblock %}

app/templates/resources/ramanbands/query.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3 content">

        {% include 'includes/backToStart.html' %}
        {% include 'includes/errors.html' %}

        <h1>{{ _('Suchen') }} <b><em>{{ _('Raman-Bande') }}</em></b></h1>
        <form method="POST" novalidate>
            {{ form.csrf_token }}
            <div class="row">
                <div class="col-12 col-md-4 mb-3">
                    {{ form.wavenumber.label(class="form-label") }}
                    {{ form.wavenumber(class="form-control", placeholder="1260") }}
                    {% if form.wavenumber.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.wavenumber.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="col-12 col-md-4 mb-3">
                    {{ form.bandType.label(class="form-label") }}
                    {{ form.bandType(class="form-control", placeholder="CH2") }}
                    {% if form.bandType.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.bandType.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="col-12 col-md-4 mb-3">
                    {{ form.bandCategory.label(class="form-label") }}
                    {{ form.bandCategory(class="form-control") }}
                    {% if form.bandCategory.errors %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for error in form.bandCategory.errors %}
                                <p class="mb-0">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

            </div>
            <button type="submit" class="btn btn-primary">{{ _('Suche starten') }}</button>
        </form>
        {% if not initial and bands|length == 0 %}
            <hr>
            <div class="mt-1">
                <p>{{ _('Es wurden keine Ergebnisse gefunden.') }}</p>
            </div>
        {% endif %}
        {% if bands|length>0 %}
            <hr>
            <h2 class="mt-1">{{ _('Ergebnisse') }}</h2>
            <table class="table table-striped table-hover table-fixed">
                <thead>
                <tr>
                    <th scope="col">{{ _('Wellenzahl [cm<sup>-1</sup>]') }}</th>
                    <th scope="col">{{ _('Schwingungsart') }}</th>
                    <th scope="col">{{ _('Kategorie') }}</th>
                    <th scope="col">{{ _('Author') }}</th>
                    <th scope="col">{{ _('DOI') }}</th>

                </tr>
                </thead>
                <tbody>
                {% for band in bands %}
                    <tr>
                        <td>{{ band.wavenumber }}</td>
                        <td>{{ band.bandAssignment.bandType }}</td>
                        <td>{{ band.bandAssignment.bandCategory.name }}</td>
                        <td>{{ band.bandAssignment.author }}</td>
                        <td><a href="{{ band.bandAssignment.doiLink }}" target="_blank">{{ _('Öffnen') }}</a></td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}