app/routes/spectral_ranges/__init__.py
from flask import Blueprint, g

bp = Blueprint('spectral_ranges', __name__)

@bp.url_defaults
def add_language_code(endpoint, values):
    if 'lang_code' not in g:
        g.lang_code = 'de'  # or your default language
    values.setdefault('lang_code', g.lang_code)


@bp.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')

from app.routes.spectral_ranges import routes

app/routes/spectral_ranges/routes.py
import sqlalchemy.exc
from flask import render_template, request, url_for, flash, redirect
from flask_login import login_required
from flask_babel import _

from app.forms.forms import SpectralRangesForm
from app.routes.spectral_ranges import bp
from app.models.model import SpectralRange
from app.extensions import db


@bp.route('/')
@login_required
def index():
    """
        Index page for spectral_ranges, only accessible for logged in users. Allowing the the user to add, edit and delete spectral_ranges

    Returns:
        rendered template of the index page, with all the spectral_ranges
    """
    spectral_ranges = db.session.query(SpectralRange).all()
    return render_template('resources/spectral_ranges/index.html', spectral_ranges=spectral_ranges)


@bp.route('/new', methods=['GET'])
@login_required
def new():
    """
        Create page for spectral_ranges, only accessible for logged in users

    Returns:
        rendered template of the new page, with the form for creating a new spectral_range
    """
    form = SpectralRangesForm()
    return render_template('resources/spectral_ranges/new.html', form=form)


@bp.route('/new', methods=['POST'])
@login_required
def new_post():
    """
        Creates a new spectral_range if form is valid, only accessible for logged in users

    Returns:
        based on the validation of the form, either redirects to this resources index page or
        renders the Create page again with validation errors (WTForms) or integrity errors (SQL constraints)
    """

    # convert request.form to form object
    form = SpectralRangesForm(request.form)
    # if the form is not valid, redirect to the new page and pass the values from the form
    if not form.validate():
        return render_template('resources/spectral_ranges/new.html', form=form)
    # if the form is valid, create a new slide and redirect to the index page
    else:
        # if unique constraint is violated, inform the user
        try:
            spectral_range = SpectralRange(start=form.start.data, end=form.end.data)
            db.session.add(spectral_range)
            db.session.commit()
            return redirect(url_for('spectral_ranges.index'))
        except sqlalchemy.exc.IntegrityError:
            flash(_('Diese Kombination aus Start und Ende existiert bereits'), 'danger')
            return render_template('resources/spectral_ranges/new.html', form=form)


@bp.route('/<spectral_range_id>/edit', methods=['GET'])
@login_required
def edit(spectral_range_id):
    """
        Edit page for spectral_ranges, only accessible for logged in users

    Args:
        spectral_range_id (int): id of the spectral_range to be edited

    Returns:
        rendered template of the edit page, with the form for editing the spectral_range
    """

    # get the spectral_range from the database and populate the form with its values
    spectral_range = db.session.query(SpectralRange).filter(SpectralRange.id == spectral_range_id).first()
    form = SpectralRangesForm(obj=spectral_range)
    return render_template('resources/spectral_ranges/edit.html', form=form)


@bp.route('/<spectral_range_id>/edit', methods=['POST'])
@login_required
def edit_post(spectral_range_id):
    """
        Edits the spectral_range if form is valid, only accessible for logged in users

    Args:
        spectral_range_id (int): id of the spectral_range to be edited

    Returns:
        based on the validation of the form, either redirects to this resources index page or
        renders the Edit page again with validation errors (WTForms) or integrity errors (SQL constraints)
    """
    # convert request.form to form object
    form = SpectralRangesForm(request.form)
    # if the form is not valid, redirect to the new page and pass the values from the form
    if not form.validate():
        return render_template('resources/spectral_ranges/edit.html', form=form)
    # if the form is valid, create a new slide and redirect to the index page
    else:
        # if unique constraint is violated, inform the user
        try:
            spectral_range = db.session.query(SpectralRange).filter(SpectralRange.id == spectral_range_id).first()
            spectral_range.start = form.start.data
            spectral_range.end = form.end.data
            db.session.commit()
            return redirect(url_for('spectral_ranges.index'))
        except sqlalchemy.exc.IntegrityError:
            flash(_('Diese Kombination aus Start und Ende existiert bereits'), 'danger')
            return render_template('resources/spectral_ranges/edit.html', form=form)


@bp.route('/<spectral_range_id>/delete')
@login_required
def delete(spectral_range_id):
    """
        Deletes the spectral_range if not used in a compound, only accessible for logged in users

    Args:
        spectral_range_id (int): id of the spectral_range to be deleted

    Returns:
       redirects to the index page, with a flash message based on the success of the deletion
    """
    try:
        spectral_range = db.session.query(SpectralRange).filter(SpectralRange.id == spectral_range_id).first()
        db.session.delete(spectral_range)
        db.session.commit()
        flash(_("Spektralbereich wurde gelöscht"), 'success')
        return redirect(url_for('spectral_ranges.index'))
    except sqlalchemy.exc.IntegrityError:
        flash(_('Dieser Spektralbereich wird noch verwendet und konnte daher nicht gelöscht werden'), 'danger')
        return redirect(url_for('spectral_ranges.index'))
    except:
        flash(_("Spektralbereich konnte nicht gelöscht werden. Probieren Sie es später erneut."), 'danger')
        return redirect(url_for('spectral_ranges.index'))

app/templates/resources/spectral_ranges/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3 content">

    <a class="icon-link icon-link-hover mb-2"
       style="--bs-icon-link-transform: translate3d(-.125rem, 0, 0); --bs-link-color-rgb: 97,100,102;"
       href="{{ url_for('spectral_ranges.index') }}">
        <i class="bi bi-arrow-left mb-auto"></i>
        {{ _('Zurück')}}
    </a>
    <h1>{{ _('Bearbeiten') }} <b><em>{{ _('Spektralbereich') }}</em></b></h1>
    {% include 'includes/errors.html' %}
    <form method="POST" novalidate>
        {{ form.csrf_token}}
        <div class="mb-3">
            <!--do custom label due to superscript-->
            <label for="{{form.start.id}}" class="form-label">{{ _('Start [cm<sup>-1</sup>]')}}</label>
            {{form.start(class="form-control", placeholder="20")}}
            {% if form.start.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.start.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="mb-3">
            <!--do custom label due to superscript-->
            <label for="{{form.end.id}}" class="form-label">{{ _('Ende [cm<sup>-1</sup>]')}}</label>
            {{form.end(class="form-control", placeholder="1500")}}
            {% if form.end.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.end.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">{{ _('Erstellen') }}</button>
    </form>
</div>
{% endblock %}

app/templates/resources/spectral_ranges/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3 content">

    {% include 'includes/backToStart.html' %}
    {% include 'includes/errors.html' %}
    <div class="row">
        <div class="col-12 col-md-6 d-flex align-items-center justify-content-start">
            <h1>{{_('Übersicht')}} <b><em>{{ _('Spektralbereich') }}</em></b></h1>
        </div>
        <div class="col-12 col-md-6 d-flex align-items-center justify-content-start justify-content-md-end">
            <a type="button" class="btn btn-outline-success btn-sm" href="{{ url_for('spectral_ranges.new') }}"><i
                    class="bi bi-plus-lg"></i>
                {{ _('Neuen Spektralbereich erstellen')}}
            </a>
        </div>
    </div>
    {% if spectral_ranges|length<=0 %}
    <h4>{{ _('Es sind noch keine Spektralbereiche hinterlegt')}}</h4>
    {% else %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">{{ _('Start [cm<sup>-1</sup>]')}}</th>
            <th>{{ _('Ende [cm<sup>-1</sup>]')}}</th>
            <th>{{ _('Aktionen') }}</th>
        </tr>
        </thead>
        <tbody>
        {% for spectral_range in spectral_ranges %}
        <tr>
            <td>{{ spectral_range.start }}</td>
            <td>{{ spectral_range.end }}</td>
            <td>
                <a type="button" class="btn btn-outline-primary btn-sm"
                   href="{{ url_for('spectral_ranges.edit', spectral_range_id=spectral_range.id) }}"><i
                        class="bi bi-pencil-fill"></i> {{ _('Bearbeiten') }}</a>
                <a type="button" class="btn btn-outline-danger btn-sm"
                   href="{{ url_for('spectral_ranges.delete', spectral_range_id=spectral_range.id) }}"><i
                        class="bi bi-trash-fill"></i> {{ _('Löschen')}}</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{% endblock %}

app/templates/resources/spectral_ranges/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3 content">

    <a class="icon-link icon-link-hover mb-2"
       style="--bs-icon-link-transform: translate3d(-.125rem, 0, 0); --bs-link-color-rgb: 97,100,102;"
       href="{{ url_for('spectral_ranges.index') }}">
        <i class="bi bi-arrow-left mb-auto"></i>
        {{ _('Zurück')}}
    </a>
    <h1>{{ _('Erstellen') }} <b><em>{{ _('Spektralbereich') }}</em></b></h1>
    {% include 'includes/errors.html' %}
    <form method="POST" novalidate>
        {{ form.csrf_token}}
        <div class="mb-3">
            <!--do custom label due to superscript-->
            <label for="{{form.start.id}}" class="form-label">{{ _('Start [cm<sup>-1</sup>]')}}</label>
            {{form.start(class="form-control", placeholder="20")}}
            {% if form.start.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.start.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="mb-3">
            <!--do custom label due to superscript-->
            <label for="{{form.end.id}}" class="form-label">{{ _('Ende [cm<sup>-1</sup>]')}}</label>
            {{form.end(class="form-control", placeholder="1500")}}
            {% if form.end.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.end.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">{{ _('Erstellen') }}</button>
    </form>
</div>
{% endblock %}