app/routes/lasers/__init__.py
from flask import Blueprint, g

bp = Blueprint('lasers', __name__)

@bp.url_defaults
def add_language_code(endpoint, values):
    if 'lang_code' not in g:
        g.lang_code = 'de'  # or your default language
    values.setdefault('lang_code', g.lang_code)


@bp.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')

from app.routes.lasers import routes

app/routes/lasers/routes.py
import sqlalchemy.exc
from flask import render_template, request, url_for, flash, redirect
from flask_babel import _

from app.forms.forms import LasersForm
from app.routes.lasers import bp
from app.models.model import Laser
from app.extensions import db
from flask_login import login_required, current_user


@bp.route('/')
@login_required
def index():
    """
        Index page for lasers, only accessible for logged in users. Allowing the user to add, edit and delete lasers

    Returns:
        rendered template of the index page, with all the lasers
        allowing the user to add, edit and delete lasers
    """
    lasers = db.session.query(Laser).all()
    return render_template('resources/lasers/index.html', lasers=lasers, name=current_user)


@bp.route('/new', methods=['GET'])
@login_required
def new():
    """
        Create page for lasers, only accessible for logged in users

    Returns:
        rendered template of the new page, with the form for creating a new laser
    """
    form = LasersForm()
    return render_template('resources/lasers/new.html', form=form)


@bp.route('/new', methods=['POST'])
@login_required
def new_post():
    """
        Creates a new laser, only accessible for logged in users

    Returns:
        based on the validation of the form, either redirects to this resources index page or
        renders the Create page again with validation errors (WTForms) or integrity errors (SQL constraints)
    """
    # convert request.form to form object
    form = LasersForm(request.form)
    # if the form is not valid, redirect to the new page and pass the values from the form
    if not form.validate():
        return render_template('resources/lasers/new.html', form=form)
    # if the form is valid, create a new lens and redirect to the index page
    else:
        # if unique constraint is violated, inform the user
        try:
            laser = Laser(wavelength=form.wavelength.data)
            db.session.add(laser)
            db.session.commit()
            return redirect(url_for('lasers.index'))
        except sqlalchemy.exc.IntegrityError:
            flash(_('Diese Wellenlänge existiert bereits'), 'danger')
            return render_template('resources/lasers/new.html', form=form)


@bp.route('/<laser_id>/edit', methods=['GET'])
@login_required
def edit(laser_id):
    """
        Edit page for lasers, only accessible for logged in users

    Args:
        laser_id (int): id of the laser to be edited

    Returns:
        rendered template of the edit page, with the form for editing a laser
    """
    laser = db.session.query(Laser).filter(Laser.id == laser_id).first()
    form = LasersForm(obj=laser)
    return render_template('resources/lasers/edit.html', form=form)


@bp.route('/<laser_id>/edit', methods=['POST'])
@login_required
def edit_post(laser_id):
    """
        Edits the laser, only accessible for logged in users

    Args:
        laser_id (int): id of the laser to be edited

    Returns:
        based on the validation of the form, either redirects to this resources index page or
        renders the Edit page again with validation errors (WTForms) or integrity errors (SQL constraints)
    """
    # convert request.form to form object
    form = LasersForm(request.form)
    # if the form is not valid, redirect to the new page and pass the values from the form
    if not form.validate():
        return render_template('resources/lasers/edit.html', form=form)
        # if the form is valid, create a new lens and redirect to the index page
    else:
        # if unique constraint is violated, inform the user
        try:
            laser = db.session.query(Laser).filter(Laser.id == laser_id).first()
            laser.wavelength = form.wavelength.data
            db.session.commit()
            return redirect(url_for('lasers.index'))
        except sqlalchemy.exc.IntegrityError:
            flash(_('Diese Wellenlänge existiert bereits'), 'danger')
            return render_template('resources/lasers/edit.html', form=form)


@bp.route('/<laser_id>/delete')
@login_required
def delete(laser_id):
    """
        Deletes the laser if not used in a compound, only accessible for logged in users

    Args:
        laser_id (int): id of the laser to be deleted

    Returns:
        redirects to the index page, with a flash message based on the success of the deletion
    """
    try:
        laser = db.session.query(Laser).filter(Laser.id == laser_id).first()
        db.session.delete(laser)
        db.session.commit()
        flash(_("Laser wurde gelöscht"), 'success')
        return redirect(url_for('lasers.index'))
    except sqlalchemy.exc.IntegrityError:
        flash(_('Dieser Laser wird noch verwendet und kann daher nicht gelöscht werden.'), 'danger')
        return redirect(url_for('lasers.index'))
    except:
        flash(_('Laser konnte nicht gelöscht werden. Probieren Sie es später erneut.'), 'danger')
        return redirect(url_for('lasers.index'))

app/templates/resources/lasers/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3 content">

    <a class="icon-link icon-link-hover mb-2"
       style="--bs-icon-link-transform: translate3d(-.125rem, 0, 0); --bs-link-color-rgb: 97,100,102;"
       href="{{ url_for('lasers.index') }}">
        <i class="bi bi-arrow-left mb-auto"></i>
        {{ _('Zurück')}}
    </a>
    <h1>{{ _('Laser bearbeiten')}}</h1>
    {% include 'includes/errors.html' %}
    <form method="POST" novalidate>
        {{form.csrf_token}}
        <div class="mb-3">
            {{ form.wavelength.label(class="form-label") }}
            {{ form.wavelength(class="form-control", placeholder="758")}}
            {% if form.wavelength.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.wavelength.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">{{ _('Speichern') }}</button>
    </form>
</div>
{% endblock %}

app/templates/resources/lasers/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3 content">

    {% include 'includes/backToStart.html' %}
    {% include 'includes/errors.html' %}
    <div class="row">
        <div class="col-12 col-md-6 d-flex align-items-center justify-content-start">
            <h1>{{_('Übersicht')}} <b><em>{{ _('Laser') }}</em></b></h1>
        </div>
        <div class="col-12 col-md-6 d-flex align-items-center justify-content-start justify-content-md-end">
            <a type="button" class="btn btn-outline-success btn-sm" href="{{ url_for('lasers.new') }}"><i
                    class="bi bi-plus-lg"></i>
                {{ _('Neuen Laser erstellen')}}
            </a>
        </div>
    </div>
    {% if lasers|length<=0 %}
    <h4>{{ _('Es sind noch keine Laser hinterlegt')}}</h4>
    {% else %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">{{ _('Wellenlänge [nm]')}}</th>
            <th>{{ _('Aktionen') }}</th>
        </tr>
        </thead>
        <tbody>
        {% for laser in lasers %}
        <tr>
            <td>{{ laser.wavelength }}</td>
            <td>
                <a type="button" class="btn btn-outline-primary btn-sm"
                   href="{{ url_for('lasers.edit', laser_id=laser.id) }}"><i class="bi bi-pencil-fill"></i>
                    {{ _('Bearbeiten') }}</a>
                <a type="button" class="btn btn-outline-danger btn-sm"
                   href="{{ url_for('lasers.delete', laser_id=laser.id) }}"><i class="bi bi-trash-fill"></i> {{ _('Löschen')}}</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{% endblock %}

app/templates/resources/lasers/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3 content">

    <a class="icon-link icon-link-hover mb-2"
       style="--bs-icon-link-transform: translate3d(-.125rem, 0, 0); --bs-link-color-rgb: 97,100,102;"
       href="{{ url_for('lasers.index') }}">
        <i class="bi bi-arrow-left mb-auto"></i>
        {{ _('Zurück')}}
    </a>

    <h1>{{ _('Erstellen') }} <b><em>{{ _('Laser') }}</em></b></h1>
    {% include 'includes/errors.html' %}
    <form method="POST" novalidate>
        {{form.csrf_token}}
        <div class="mb-3">
            {{ form.wavelength.label(class="form-label") }}
            {{ form.wavelength(class="form-control", placeholder="758")}}
            {% if form.wavelength.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.wavelength.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">{{ _('Erstellen') }}</button>
    </form>
</div>
{% endblock %}